
Train 0/200
Traceback (most recent call last):
  File "D:\challege_ai\baseline\train.py", line 140, in <module>
    trainer.train(train_l_loader=train_l_loader, train_u_loader=train_u_loader)
  File "D:\challege_ai\baseline\modules\trainer.py", line 87, in train
    pred_u, rep_u = self.model(train_u_aug_data)
  File "C:\Users\rudwn\anaconda3\envs\deeplearning\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\challege_ai\baseline\models\deeplabv3\deeplabv3.py", line 81, in forward
    prediction = self.classifier(torch.cat([x_low, output_feature], dim=1))
  File "C:\Users\rudwn\anaconda3\envs\deeplearning\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\rudwn\anaconda3\envs\deeplearning\lib\site-packages\torch\nn\modules\container.py", line 141, in forward
    input = module(input)
  File "C:\Users\rudwn\anaconda3\envs\deeplearning\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\rudwn\anaconda3\envs\deeplearning\lib\site-packages\torch\nn\modules\conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\rudwn\anaconda3\envs\deeplearning\lib\site-packages\torch\nn\modules\conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Unable to find a valid cuDNN algorithm to run convolution